# Generated by Django 3.2.4 on 2021-06-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
