# Generated by Django 3.2.4 on 2021-06-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='payment_option',
            field=models.CharField(default='paytm', max_length=100),
            preserve_default=False,
        ),
    ]
