# Generated by Django 3.2.4 on 2021-06-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_billing_address_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.billing_address'),
        ),
    ]
