# Generated by Django 3.2.4 on 2021-06-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20210619_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='payment_option',
        ),
    ]
