# Generated by Django 3.2.4 on 2021-06-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=1000)),
            ],
        ),
    ]
