# Generated by Django 3.2.4 on 2021-07-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20210626_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
    ]
