# Generated by Django 3.2.4 on 2021-07-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_billing_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
