# Generated by Django 3.2.4 on 2021-07-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_auto_20210720_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
