# Generated by Django 3.2.4 on 2021-07-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
