# Generated by Django 3.2.4 on 2021-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='score',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
