# Generated by Django 3.2.4 on 2021-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_billing_address_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='score',
        ),
        migrations.AddField(
            model_name='billing_address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
