# Generated by Django 3.2.4 on 2021-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_remove_billing_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(blank=True, max_length=1000000000000, null=True),
        ),
    ]
