# Generated by Django 3.2.4 on 2021-08-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_auto_20210727_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
