# Generated by Django 3.2.4 on 2021-08-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0029_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
