# Generated by Django 3.2.4 on 2021-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0031_item_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.CharField(blank=True, choices=[('250 gm', '250 gm'), ('255 gm', '255 gm'), ('1 kg', '1 kg'), ('3 kg', '3 kg')], max_length=1000, null=True),
        ),
    ]
