# Generated by Django 3.2.4 on 2021-08-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0033_item_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.CharField(blank=True, choices=[('200 gm', '200 gm'), ('255 gm', '255 gm'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg')], max_length=1000, null=True),
        ),
    ]
