# Generated by Django 3.2.4 on 2021-08-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0034_auto_20210824_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.CharField(blank=True, choices=[('200 gm', '200 gm'), ('255 gm', '255 gm'), ('260 gm', '260 gm'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg'), ('60 Capsules', '60 Capsules')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.description'),
        ),
    ]
