# Generated by Django 3.2.4 on 2021-08-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0035_auto_20210824_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='beforePrice',
            field=models.IntegerField(default=0),
        ),
    ]
