# Generated by Django 3.2.4 on 2021-08-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0038_item_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='beforePrice',
        ),
    ]
