# Generated by Django 3.2.4 on 2021-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0040_item_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
