# Generated by Django 3.2.4 on 2021-08-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0041_alter_item_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
