# Generated by Django 3.2.4 on 2021-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0043_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Preworkout', 'Preworkout'), ('Intraworkout', 'Intraworkout'), ('Protein', 'Protein'), ('Gainer', 'Gainer'), ('Other ', 'Other ')], max_length=1000, null=True),
        ),
    ]
