# Generated by Django 3.2.4 on 2021-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0044_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='beforePrice',
            field=models.IntegerField(default=1000),
        ),
    ]
