# Generated by Django 3.2.4 on 2021-09-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0048_auto_20210902_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.item'),
        ),
    ]
