# Generated by Django 3.2.4 on 2021-09-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0051_item_beforeprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='beforePrice',
        ),
    ]
