# Generated by Django 3.2.4 on 2021-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0052_remove_item_beforeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='beforePrice',
            field=models.IntegerField(default=0),
        ),
    ]
