# Generated by Django 3.2.4 on 2021-09-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0053_item_beforeprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='beforePrice',
            new_name='afterPrice',
        ),
    ]
