# Generated by Django 3.2.4 on 2021-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0054_rename_beforeprice_item_afterprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='afterPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
