# Generated by Django 3.2.4 on 2021-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0055_alter_item_afterprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Preworkout', 'Preworkout'), ('Intraworkout', 'Intraworkout'), ('Protein', 'Protein'), ('Gainer', 'Gainer'), ('Other', 'Other')], max_length=1000, null=True),
        ),
    ]
