# Generated by Django 3.2.4 on 2021-09-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0056_auto_20210916_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final',
            field=models.IntegerField(default=0),
        ),
    ]
