# Generated by Django 3.2.4 on 2021-09-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0057_order_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final',
        ),
    ]
