# Generated by Django 3.2.4 on 2021-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0058_remove_order_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
