# Generated by Django 3.2.4 on 2021-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0059_order_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
