# Generated by Django 3.2.4 on 2021-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0060_alter_order_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
