# Generated by Django 3.2.4 on 2021-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0061_alter_order_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final',
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.IntegerField(default=0),
        ),
    ]
