# Generated by Django 3.2.4 on 2021-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0063_finalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FinalAmount',
        ),
    ]
