# Generated by Django 3.2.4 on 2021-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0064_auto_20211001_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
