# Generated by Django 3.2.4 on 2021-10-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0067_alter_order_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.AddField(
            model_name='coupons',
            name='order_items',
            field=models.ManyToManyField(to='basic.OrderItem'),
        ),
    ]
