# Generated by Django 3.2.4 on 2021-10-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0068_auto_20211025_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='order_items',
            field=models.ManyToManyField(to='basic.Order'),
        ),
    ]
