# Generated by Django 3.2.4 on 2021-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0069_alter_coupons_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='tag',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.CharField(blank=True, choices=[('200 gm', '200 gm'), ('255 gm', '255 gm'), ('260 gm', '260 gm'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg'), ('60 Capsules', '60 Capsules'), ('L', 'L'), ('XL', 'XL')], max_length=1000, null=True),
        ),
    ]
